package edu.nyu.cs6103.movietickets.client.controller;
import edu.nyu.cs6103.movietickets.client.SceneManager; import edu.nyu.cs6103.movietickets.shared.*; import edu.nyu.cs6103.movietickets.shared.dto.*;
import javafx.fxml.FXML; import javafx.scene.control.*; import java.math.BigDecimal; import java.time.LocalDateTime; import java.time.format.DateTimeFormatter;
public final class ShowtimeManagementController extends AbstractClientController {
 @FXML private ComboBox<MovieDto> movieBox; @FXML private ComboBox<TheaterDto> theaterBox; @FXML private ListView<ShowtimeDto> list; @FXML private TextField dateTimeField,priceField; @FXML private ComboBox<String> statusBox; @FXML private Label statusLabel; private ShowtimeDto selected;
 private static final DateTimeFormatter FORMAT=DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
 @Override protected void onShow(Object p){movieBox.setCellFactory(v->movieCell());movieBox.setButtonCell(movieCell());theaterBox.setCellFactory(v->theaterCell());theaterBox.setButtonCell(theaterCell());list.setCellFactory(v->new ListCell<>(){protected void updateItem(ShowtimeDto s,boolean e){super.updateItem(s,e);setText(e||s==null?null:"#"+s.id()+"  "+s.startTime().format(FORMAT)+"  $"+s.price()+"  "+s.status());}});statusBox.getItems().setAll("SCHEDULED","CANCELLED");statusBox.setValue("SCHEDULED");movieBox.setOnAction(e->refreshShowtimes());list.getSelectionModel().selectedItemProperty().addListener((o,a,s)->populate(s));loadOptions();}
 private ListCell<MovieDto> movieCell(){return new ListCell<>(){protected void updateItem(MovieDto m,boolean e){super.updateItem(m,e);setText(e||m==null?null:m.title());}};} private ListCell<TheaterDto> theaterCell(){return new ListCell<>(){protected void updateItem(TheaterDto t,boolean e){super.updateItem(t,e);setText(e||t==null?null:t.name());}};}
 private void loadOptions(){runNetwork(()->new NetworkResponse[]{client.send(RequestType.GET_MOVIES,null),client.send(RequestType.GET_THEATERS,null)},a->{if(requireSuccess(a[0])&&requireSuccess(a[1])){movieBox.getItems().setAll(client.responseData(a[0],MovieListResponse.class).movies());theaterBox.getItems().setAll(client.responseData(a[1],TheaterDto[].class));if(!movieBox.getItems().isEmpty())movieBox.getSelectionModel().selectFirst();}},statusLabel);}
 private void refreshShowtimes(){MovieDto m=movieBox.getValue();if(m==null)return;runNetwork(()->client.send(RequestType.GET_SHOWTIMES,new ShowtimeRequest(m.id())),r->{if(requireSuccess(r))list.getItems().setAll(client.responseData(r,ShowtimeListResponse.class).showtimes());},statusLabel);}
 private void populate(ShowtimeDto s){selected=s;if(s==null)return;movieBox.getItems().stream().filter(m->m.id()==s.movieId()).findFirst().ifPresent(movieBox::setValue);theaterBox.getItems().stream().filter(t->t.id()==s.theaterId()).findFirst().ifPresent(theaterBox::setValue);dateTimeField.setText(s.startTime().format(FORMAT));priceField.setText(s.price().toPlainString());statusBox.setValue(s.status());}
 @FXML private void clear(){selected=null;dateTimeField.clear();priceField.clear();statusBox.setValue("SCHEDULED");list.getSelectionModel().clearSelection();}
 @FXML private void save(){try{MovieDto m=movieBox.getValue();TheaterDto t=theaterBox.getValue();if(m==null||t==null)throw new IllegalArgumentException();AdminShowtimeRequest d=new AdminShowtimeRequest(selected==null?0:selected.id(),m.id(),t.id(),LocalDateTime.parse(dateTimeField.getText(),FORMAT),new BigDecimal(priceField.getText()),statusBox.getValue());RequestType type=selected==null?RequestType.ADMIN_CREATE_SHOWTIME:RequestType.ADMIN_UPDATE_SHOWTIME;runNetwork(()->client.send(type,d),r->{if(requireSuccess(r)){clear();refreshShowtimes();}},statusLabel);}catch(Exception e){statusLabel.setText("Use date/time yyyy-MM-dd HH:mm and a valid price.");}}
 @FXML private void back(){scenes.show(SceneManager.View.ADMIN_DASHBOARD);}
}
