package edu.nyu.cs6103.movietickets.shared;

public enum RequestType {
    REGISTER,
    LOGIN,
    LOGOUT,
    GET_MOVIES,
    GET_MOVIE,
    GET_THEATERS,
    GET_THEATER,
    GET_SHOWTIMES,
    GET_SEAT_MAP,
    LOCK_SEATS,
    RELEASE_SEATS,
    CREATE_BOOKING,
    CANCEL_BOOKING,
    GET_BOOKING_HISTORY,
    ADMIN_CREATE_MOVIE,
    ADMIN_UPDATE_MOVIE,
    ADMIN_CREATE_THEATER,
    ADMIN_UPDATE_THEATER,
    ADMIN_CREATE_SHOWTIME,
    ADMIN_UPDATE_SHOWTIME
}
